### ISSUE TITLE
Not work...

### ISSUE THREAD

**Issue by ShadowComes** [MYSK84FUN/Save.dat-Stealer-Builder#1]
Hello there! I maked new webhook and pasted in to text box... But when i build it and open... it wont send me the save.dat, SetReg.reg fiels.... even screenshots.... Can pls fix that?

**Comment by MYSK84FUN** [comment]
> Hello there! I maked new webhook and pasted in to text box... But when i build it and open... it wont send me the save.dat, SetReg.reg fiels.... even screenshots.... Can pls fix that?

Maybe the source pastebin link has been expired or has been taked down.
Try replacing the pastebin link
